version: 2
updates:
  - package-ecosystem: "terraform"
    directory: "/"
    allow:
      - dependency-type: "all"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "10:00"
      timezone: "Australia/Melbourne"
